apiVersion: v1
kind: Service
metadata:
  name: document-center-be-service
  namespace: document-center
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: document-center-be

