apiVersion: v1
kind: Service
metadata:
  name: document-center-be-service
  namespace: document-center
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: document-center-be

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: document-center-be-ingress
  namespace: document-center
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - http:
      paths:
      - path: /document-center
        pathType: Prefix
        backend:
          service:
            name: document-center-be-service
            port:
              number: 80
