name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'k8s/**'
  pull_request:
    branches:
      - '*'

jobs:
  scan:
    if: github.event_name == 'pull_request' || (github.event_name == 'push' && github.ref == 'refs/heads/main')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - uses: snyk/actions/setup@master
      - name: Snyk monitor
        run: snyk test --json > snyk-report.json
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Save Snyk results
        uses: actions/upload-artifact@v4
        with:
          name: snyk-results
          path: snyk-report.json

  test:
    if: github.event_name == 'pull_request' || (github.event_name == 'push' && github.ref == 'refs/heads/main')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: List the state of node modules
        if: steps.cache-npm.outputs.cache-hit == 'false'
        continue-on-error: true
        run: npm list
      - run: npm ci --legacy-peer-deps
      - run: npm run build
      - run: npm test
        env:
          CI: true
      - name: Run unit tests and generate coverage report
        run: |
          npx jest --coverage

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: ./coverage

  build-and-push:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: [test, scan]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: yjack0000cs12/document-center-be:v${{ github.run_number }}
      - name: Update k8s config
        run: |
          sed -i "s|yjack0000cs12/document-center-be:v[0-9]*|yjack0000cs12/document-center-be:v${{ github.run_number }}|" ./k8s/deploys.yml
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git          
          git add ./k8s/deploys.yml
          git commit -m "Update deployment image to v${{ github.run_number }}"
          git push
